name: CV
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SASS syntax compatibility
        run: |
          echo "Searching for cv.scss and main.scss files..."
          find "${{ github.workspace }}" -type f \( -name "cv.scss" -o -name "main.scss" \) -exec echo "Found: {}" \;

          echo "Applying @use to @import replacement..."
          find "${{ github.workspace }}" -type f \( -name "cv.scss" -o -name "main.scss" \) -exec sed -i 's/@use/@import/g' {} +

          echo "Verifying replacements..."
          find "${{ github.workspace }}" -type f \( -name "cv.scss" -o -name "main.scss" \) -exec grep '@import' {} \; || echo "No @import replacements found"

          echo "Displaying file contents after replacement:"
          find "${{ github.workspace }}" -type f \( -name "cv.scss" -o -name "main.scss" \) -exec echo "Contents of {}:" \; -exec cat {} \;

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Initialize bundle
        run: |
          bundle lock --add-platform "$(ruby -e 'puts RUBY_PLATFORM')"
          bundle install

      - name: Build
        run: bundle exec jekyll build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          enable_jekyll: true
