name: GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: SASS syntax compatibility
        run: |
          for file in assets/main.scss _sass/cv.scss; do
            if [ -f "$file" ]; then
              sed -i 's/@use/@import/g' "$file"
            fi
          done

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Initialize bundle
        run: |
          bundle lock --add-platform "$(ruby -e 'puts RUBY_PLATFORM')"
          bundle install

      - name: Build
        run: bundle exec jekyll build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          enable_jekyll: true